# Generated by Django 4.1.3 on 2022-12-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_category_address_order_product_wishlist_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupan_code', models.CharField(max_length=25)),
                ('start_date_and_time', models.DateTimeField()),
                ('end_date_and_time', models.DateTimeField()),
                ('discount_amount', models.CharField(blank=True, max_length=5)),
                ('discount_percentage', models.CharField(blank=True, max_length=5)),
                ('maximum_usage', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupan_applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupan', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_and_time', models.DateField()),
                ('end_date_and_time', models.DateField()),
                ('discount_amount', models.CharField(blank=True, max_length=5)),
                ('discount_percentage', models.CharField(blank=True, max_length=5)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.add_category')),
            ],
        ),
    ]
